### PR TITLE
Added Combined Air Emissions, Greenhouse Gases and Toxic Releases.  A…

### PR DESCRIPTION
**Pull request by shansen5**
…dded facility name, lat and long to all exportable CSVs of program data.

Addresses issues #34 and #35.

### CODE REVIEW

**Comment by ericnost** [comment]
Reviewing now

**Comment by ericnost** [comment]
Hi @shansen5 - generally everything looks good. I added a few commits that will address other issues. I ran into an error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-b39839100b5d> in <module>()
     96 data_set_choices = []
     97 for k, v in data_sets.items():
---> 98     if ( v.has_echo_flag( echo_data ) ):
     99         data_set_choices.append( k )
    100 

~/Documents/GitHub/ECHO-Cross-Program/ECHO-modules/DataSet.py in has_echo_flag(self, echo_data)
     97             echo_flag = 'SDWIS_FLAG'
     98         else:
---> 99             echo_flag = self.echo_type + '_FLAG'
    100         my_echo_data = echo_data[ echo_data[ echo_flag ] == 'Y' ]
    101         return len( my_echo_data ) > 0

TypeError: can only concatenate list (not "str") to list
```

I wonder what's going on here. I was using a fresh copy of ECHO-modules. Is it possible there's a commit to DataSet.py that you haven't made yet? I was testing on NY-1 Congressional District.

**Comment by shansen5** [comment]
> Hi @shansen5 - generally everything looks good. I added a few commits that will address other issues. I ran into an error when creating the data classes:
> 
> ```
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-9-b39839100b5d> in <module>()
>      96 data_set_choices = []
>      97 for k, v in data_sets.items():
> ---> 98     if ( v.has_echo_flag( echo_data ) ):
>      99         data_set_choices.append( k )
>     100 
> 
> ~/Documents/GitHub/ECHO-Cross-Program/ECHO-modules/DataSet.py in has_echo_flag(self, echo_data)
>      97             echo_flag = 'SDWIS_FLAG'
>      98         else:
> ---> 99             echo_flag = self.echo_type + '_FLAG'
>     100         my_echo_data = echo_data[ echo_data[ echo_flag ] == 'Y' ]
>     101         return len( my_echo_data ) > 0
> 
> TypeError: can only concatenate list (not "str") to list
> ```
> 
> I wonder what's going on here. I was using a fresh copy of ECHO-modules. Is it possible there's a commit to DataSet.py that you haven't made yet? I was testing on NY-1 Congressional District.

I had committed a change to DataSet.py but the push may not have worked.  Try again.  Be sure to remove your local ECHO-modules before running, so the first cell will clone the latest.

**Comment by ericnost** [comment]
@shansen5 Got it! Going to try now.

**Comment by ericnost** [comment]
@shansen5 I got further this time, but run into errors in this section:

```
# Find the facility that matches the program data, by REGISTRY_ID.  
# Add lat and lon, facility name and REGISTRY_ID as fac_registry_id.
# (The program data may alread have a REGISTRY_ID field.)
```
For instance, when I run NY-1 RCRA Violations, Inspections, Enforcements, Air Compliance, Water Quality Violations I get this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-41-39f86488fd5a> in <module>()
     37     fac_id = fac.Index
     38     try:
---> 39         program_rows = program_data.loc[ fac_id ].copy()
     40         n = program_rows.shape[0]
     41         fac_list = [fac.Index] * n
......
TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [110006701122] of <class 'int'>
```
If I do `str(fac_id)` then the code resolves but the output is: `_____` (empty data frame) I *_think_ the problem is* that we are using the index of `echo_data` (which is `REGISTRY_ID`) to match with the index of `program_data` which is not necessarily `REGISTRY_ID` 

When I run Air Inspections, Combined Air Emissions, Air Enforcements, Greenhouse Emissions, Toxic Emissions I get this error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-39f86488fd5a> in <module>()
      5 if ( program.name == "Air Inspections" or program.name == "Air Enforcements" ):
      6     # The REGISTRY_ID field is the index of the echo_data
----> 7     registry_ids = echo_data[echo_data['AIR_FLAG'] == 'Y'].index.to_list()
      8     program_data = program.get_data( ee_ids=registry_ids )
      9 elif ( program.name == "Combined Air Emissions" ):

AttributeError: 'Int64Index' object has no attribute 'to_list'
```
Switching `...index.to_list()` to `....index.values` fixed the problem for me, but then the output is just `___` (empty data frame)

When I run Air Violations, Air Formal Actions the code resolves but the output is just `___` (empty data frame)

**Comment by ericnost** [comment]
Basically, I can only get this to work for GHG emissions in NY-1. When I run Combined Air Emissions, I get:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-79-d6801f95b11f> in <module>()
     10     ghg_registry_ids = echo_data[echo_data['GHG_FLAG'] == 'Y'].index.values
     11     tri_registry_ids = echo_data[echo_data['TRI_FLAG'] == 'Y'].index.values
---> 12     id_set = set( ghg_registry_ids + tri_registry_ids )
     13     program_data = program.get_data( ee_ids=list(id_set) )
     14 elif ( program.name == "Greenhouse Gases" or program.name == "Toxic Releases" ):

ValueError: operands could not be broadcast together with shapes (10,) (19,) 
```

When I run Toxic Releases, I get:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-80-d6801f95b11f> in <module>()
     37     fac_id = fac.Index
     38     try:
---> 39         program_rows = program_data.loc[ fac_id ].copy()
     40         n = program_rows.shape[0]
     41         fac_list = [fac.Index] * n

AttributeError: 'NoneType' object has no attribute 'loc'
```

I think because there are no TRI facilities (just need a way to handle that)

**Comment by ericnost** [comment]
@shansen5 Could you checkout `ghg_and_locations` again and take a look? I think I have a solution, but I also lost sight of what we were trying to accomplish in the section giving us trouble. It's also not necessarily an efficient solution (water quality violations take a while), but I think it does work.

I tested it on SDWA visits, Greenhouse Gases, Air Inspections, RCRA violations, and Water Quality Violations.

Note that I made changes only to the area-wide part of the notebook. If it works there, we can apply to the individual facility section too?

Problem for another time, but in the `df_to_map` section (mapping facilities only in this program), we could use `my_prog_data` and style markers based on program data.

**Comment by shansen5** [comment]
> @shansen5 Could you checkout `ghg_and_locations` again and take a look? **I think I have a solution**, but I also lost sight of what we were trying to accomplish in the section giving us trouble. It's also not necessarily an efficient solution (water quality violations take a while), but I think it does work.
> 
> I tested it on SDWA visits, Greenhouse Gases, Air Inspections, RCRA violations, and Water Quality Violations.
> 
> Note that I made changes only to the area-wide part of the notebook. If it works there, we can apply to the individual facility section too?
> 
> Problem for another time, but in the `df_to_map` section (mapping facilities only in this program), we could use `my_prog_data` and style markers based on program data.

I ran through a few cases and it seems to work well.  This section is pretty impressive!
```
        try:
            echo_row = pd.DataFrame(echo_data.loc[reg_id].copy()).T.reset_index() # Find and filter to the corresponding row in ECHO_EXPORTER
            echo_row = echo_row[['FAC_NAME', 'FAC_LAT', 'FAC_LONG']] # Keep only the columns we need
            program_row =  pd.DataFrame([list(fac)[1:]], columns=program_data.columns.values) # Turn the program_data tuple into a DataFrame
            full_row = pd.concat([program_row, echo_row], axis=1) # Join the EE row df and the program row df
            frames = [my_prog_data, full_row]
            my_prog_data = pd.concat( frames, ignore_index=False)
```
How did you come up with that?

**Comment by ericnost** [comment]
@maalvikabhat - do you have some time to review @shansen5's additions? You would check out the `ghg_and_locations` branch and test the notebook for a few geographies/data types to make sure things run smoothly. If all looks good you can "approve" the changes and go ahead and merge the pull request. If there are some quick fixes, you can make your own commits and then approve and pull.

**Comment by shansen5** [comment]
@ericnost @maalvikabhat @Frijol Can we merge this branch into the master?

**Comment by ericnost** [comment]
@shansen5 Yes, let's go ahead and do that!

**Comment by Frijol** [comment]
Sorry I've not had a chance to do code reviews later! Trying to balance my EDGI hours, hoping to get back into the notebooks space in the next weeks

**Pull request merged**
